trigger: none
pr: none
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: resource
    displayName: "Wybierz zasób do utworzenia"
    type: string
    default: "Vm"
    values:
    - Vm
    - aks
  - name: action
    type: string
    values:
    - apply
    - delete
  - name: environment
    type: string
    values:
    - prod
    - dev
stages:
  - stage: deploy-dev
    condition: eq(parameters.environment, "dev")
    jobs:
      - template: ../templates/terraform-apply.yaml
  - stage: deploy-prod
    condition: eq(parameters.environment, "prod")
    jobs:
      - template: ../templates/terraform-apply-approval.yaml
    