trigger: none
pr: none
pool:
  vmImage: 'ubuntu-latest'
parameters:
  - name: resource
    displayName: "Wybierz zasób do utworzenia"
    type: string
    default: "Vm"
    values:
    - Vm
    - aks
  - name: action
    type: string
    default: "apply"
    values:
    - apply
    - delete
  - name: environment
    type: string
    default: "dev"
    values:
    - prod
    - dev
stages:
- stage: terraformPlan
  jobs:
    - template: ../templates/terraform-plan.yaml
      parameters:
        resource: ${{ parameters.resource }}
- stage: terraformDeploy
  jobs:
    - template: ../templates/terraform-apply.yaml
      parameters:
        environment: ${{ parameters.environment }}
        resource: ${{ parameters.resource }}
        action: ${{ parameters.action }}
    